-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.profiles
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    phone_number character varying(20) COLLATE pg_catalog."default",
    instagram_handle character varying(100) COLLATE pg_catalog."default",
    postcode character varying(20) COLLATE pg_catalog."default",
    home_course character varying(100) COLLATE pg_catalog."default",
    handicap numeric(4, 1),
    skill_level character varying(50) COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    updated_at timestamp without time zone DEFAULT now(),
    availability character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT profiles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.round_requests
(
    id uuid NOT NULL,
    round_id uuid NOT NULL,
    requester_id uuid NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT round_requests_pkey PRIMARY KEY (id),
    CONSTRAINT unique_round_request UNIQUE (round_id, requester_id)
);

CREATE TABLE IF NOT EXISTS public.rounds
(
    id uuid NOT NULL,
    creator_id uuid,
    course_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    round_date date NOT NULL,
    tee_time time without time zone NOT NULL,
    players_needed integer NOT NULL,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    is_active boolean DEFAULT true,
    max_players integer DEFAULT 4,
    CONSTRAINT rounds_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    full_name character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.round_requests
    ADD CONSTRAINT round_requests_requester_id_fkey FOREIGN KEY (requester_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.round_requests
    ADD CONSTRAINT round_requests_round_id_fkey FOREIGN KEY (round_id)
    REFERENCES public.rounds (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rounds
    ADD CONSTRAINT rounds_creator_id_fkey FOREIGN KEY (creator_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;